### ISSUE TITLE
[BUG] Phone number in Self Register flow is null

### ISSUE THREAD

**Issue by 274188A** [fretje/heroplate#8]
**Describe the bug**
User tries to self Register
https://localhost:5002/users/self-register

**To Reproduce**
Fill out form for a new Registered user, click save

**Exception**
>System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByNameAsync(String normalizedUserName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.<FindByNameAsync>d__76.MoveNext()
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateUserName>d__6.MoveNext()
   at Microsoft.AspNetCore.Identity.UserValidator`1.<ValidateAsync>d__5.MoveNext()
   at Microsoft.AspNetCore.Identity.UserManager`1.<ValidateUserAsync>d__174.MoveNext()
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__72.MoveNext()
   at Microsoft.AspNetCore.Identity.UserManager`1.<CreateAsync>d__77.MoveNext()
   at Heroplate.Api.Infrastructure.Identity.UserService.<CreateAsync>d__2.MoveNext() in D:\repos\heroplate\src\Api\Api.Infrastructure\Identity\UserService.CreateUpdate.cs:line 26

**Comment by 274188A** [comment]
line 24:
..\src\Api\Api.Infrastructure\Identity\UserService.CreateUpdate.cs

**Comment by 274188A** [comment]
obviously i needed to set up the tenant first
